"""init schema

Revision ID: bfab7ff5e53e
Revises: 
Create Date: 2025-07-11 14:32:20.558135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfab7ff5e53e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('nama_barang', sa.String(length=100), nullable=True),
    sa.Column('jenis_transaksi', sa.String(length=20), nullable=True),
    sa.Column('jumlah', sa.Float(), nullable=True),
    sa.Column('sumber', sa.String(length=50), nullable=True),
    sa.Column('referensi_id', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_stok')
    # ### end Alembic commands ###
